"""Input-shaping archive — a persistent, on-host record of resonance captures and the
``[input_shaper]`` configs generated from them, so past results can be reviewed,
re-analysed, downloaded or deleted instead of living only in ``/tmp`` + the browser's
localStorage.

Each run is a folder ``<data_dir>/input-shaper-archive/<run_id>/`` holding the saved
file(s) — a copied resonance CSV and/or an ``input_shaper.cfg`` — plus a compact summary;
a single ``index.json`` at the archive root lists every run (summary only, never the
multi-thousand-element PSD / spectrogram arrays, so the index stays tiny on the Pi).
Retention is bounded **per kind** (older runs are pruned) to stay light on the SD card.

Mirrors the ``devices_store`` / ``firmware_profiles`` patterns: atomic writes, graceful
reads, a name regex + ``realpath`` containment guard against path traversal.
"""

from __future__ import annotations

import contextlib
import json
import os
import re
import shutil
from datetime import datetime
from typing import Any

#: Run ids are generated by us as ``<YYYY-MM-DD_HH-MM-SS>_<kind>[_<axis>]`` — only these
#: characters ever appear, and the guard rejects anything path-traversing.
_RUN_ID_RE = re.compile(r"^[A-Za-z0-9_.\-]+$")
_KINDS = ("shaper", "noise", "belts", "axes_map", "static", "vibrations", "config")
_CONFIG_FILE = "input_shaper.cfg"


class ArchiveError(ValueError):
    """Raised on an invalid run id / filename (empty, malformed, or path-traversing)."""


def archive_dir(data_dir: str) -> str:
    """Returns (creating if needed) the archive root directory."""
    path = os.path.join(os.path.expanduser(data_dir), "input-shaper-archive")
    os.makedirs(path, exist_ok=True)
    return path


def _index_path(data_dir: str) -> str:
    return os.path.join(archive_dir(data_dir), "index.json")


def validate_run_id(run_id: str) -> str:
    """Validates a generated run id (guards against path traversal) and returns it."""
    if not run_id or ".." in run_id or not _RUN_ID_RE.match(run_id):
        raise ArchiveError(f"Invalid run id {run_id!r}")
    return run_id


def validate_filename(name: str) -> str:
    """Rejects a path-traversing file name. Permits the ``=`` / ``,`` that appear in
    Klipper's belt-vector capture names (the real guard is realpath containment below)."""
    if not name or name in (".", "..") or ".." in name or "/" in name or "\\" in name:
        raise ArchiveError(f"Invalid file name {name!r}")
    return name


def _run_dir(data_dir: str, run_id: str) -> str:
    return os.path.join(archive_dir(data_dir), validate_run_id(run_id))


def read_index(data_dir: str) -> list[dict[str, Any]]:
    """Returns the saved runs, newest-first (empty if none / unreadable)."""
    try:
        with open(_index_path(data_dir)) as handle:
            data = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(data, list):
        return []
    runs = [r for r in data if isinstance(r, dict) and r.get("id")]
    return sorted(runs, key=lambda r: str(r.get("id", "")), reverse=True)


def _write_index(data_dir: str, runs: list[dict[str, Any]]) -> None:
    """Atomically writes the archive index."""
    path = _index_path(data_dir)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = f"{path}.tmp"
    with open(tmp, "w") as handle:
        json.dump(runs, handle, indent=2)
    os.replace(tmp, path)


def _dir_size(path: str) -> int:
    total = 0
    for root, _dirs, files in os.walk(path):
        for name in files:
            with contextlib.suppress(OSError):
                total += os.path.getsize(os.path.join(root, name))
    return total


def _make_run_id(kind: str, axis: str | None, existing: set[str]) -> str:
    stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    base = f"{stamp}_{kind}" + (f"_{axis}" if axis else "")
    run_id = base
    suffix = 2
    while run_id in existing:  # sub-second collisions (mostly tests) get a counter
        run_id = f"{base}_{suffix}"
        suffix += 1
    return validate_run_id(run_id)


def _prune(data_dir: str, index: list[dict[str, Any]], keep_n: int) -> list[dict[str, Any]]:
    """Keeps the newest ``keep_n`` runs PER KIND; deletes the rest from disk + index."""
    by_kind: dict[str, int] = {}
    kept: list[dict[str, Any]] = []
    for run in sorted(index, key=lambda r: str(r.get("id", "")), reverse=True):
        kind = str(run.get("kind", "shaper"))
        count = by_kind.get(kind, 0)
        if count < keep_n:
            by_kind[kind] = count + 1
            kept.append(run)
        else:
            shutil.rmtree(_run_dir(data_dir, run["id"]), ignore_errors=True)
    return kept


def save_run(
    data_dir: str,
    *,
    kind: str,
    axis: str | None = None,
    summary: dict[str, Any] | None = None,
    config_text: str | None = None,
    csv_sources: list[str] | None = None,
    keep_n: int = 20,
) -> dict[str, Any]:
    """Creates an archive run: copies any ``csv_sources`` in, writes ``config_text`` (if
    given), records a compact summary, then prunes the kind to ``keep_n``."""
    safe_kind = kind if kind in _KINDS else "shaper"
    index = read_index(data_dir)
    run_id = _make_run_id(safe_kind, axis, {str(r["id"]) for r in index})
    run_path = _run_dir(data_dir, run_id)
    os.makedirs(run_path, exist_ok=True)

    files: list[str] = []
    for src in csv_sources or []:
        if os.path.isfile(src):
            base = validate_filename(os.path.basename(src))
            shutil.copyfile(src, os.path.join(run_path, base))
            files.append(base)
    if config_text is not None:
        with open(os.path.join(run_path, _CONFIG_FILE), "w") as handle:
            handle.write(config_text)
        files.append(_CONFIG_FILE)

    record: dict[str, Any] = {
        "id": run_id,
        "at": datetime.now().isoformat(timespec="seconds"),
        "kind": safe_kind,
        "axis": axis,
        "summary": summary or {},
        "files": files,
        "size": _dir_size(run_path),
    }
    index.append(record)
    _write_index(data_dir, _prune(data_dir, index, keep_n))
    return record


def attach_config(data_dir: str, run_id: str, config_text: str) -> dict[str, Any] | None:
    """Writes ``input_shaper.cfg`` into an existing run, returning the updated record."""
    validate_run_id(run_id)
    index = read_index(data_dir)
    for run in index:
        if run["id"] == run_id:
            run_path = _run_dir(data_dir, run_id)
            os.makedirs(run_path, exist_ok=True)
            with open(os.path.join(run_path, _CONFIG_FILE), "w") as handle:
                handle.write(config_text)
            files = run.setdefault("files", [])
            if _CONFIG_FILE not in files:
                files.append(_CONFIG_FILE)
            run["size"] = _dir_size(run_path)
            _write_index(data_dir, index)
            return run
    return None


def save_config_run(
    data_dir: str,
    *,
    config_text: str,
    axis: str | None = None,
    summary: dict[str, Any] | None = None,
    run_id: str | None = None,
    keep_n: int = 20,
) -> dict[str, Any]:
    """Saves a generated config — attached to ``run_id`` if given + present, else a new run."""
    if run_id:
        attached = attach_config(data_dir, run_id, config_text)
        if attached is not None:
            return attached
    return save_run(
        data_dir, kind="config", axis=axis, summary=summary, config_text=config_text, keep_n=keep_n
    )


def get_run(data_dir: str, run_id: str) -> dict[str, Any] | None:
    """Returns a run record plus its inline config text (if any), or None."""
    validate_run_id(run_id)
    for run in read_index(data_dir):
        if run["id"] == run_id:
            record = dict(run)
            cfg = os.path.join(_run_dir(data_dir, run_id), _CONFIG_FILE)
            if os.path.isfile(cfg):
                try:
                    with open(cfg) as handle:
                        record["config_text"] = handle.read()
                except OSError:
                    record["config_text"] = None
            return record
    return None


def run_file_path(data_dir: str, run_id: str, filename: str) -> str | None:
    """The on-disk path of a file in a run, validated to resolve inside the run dir."""
    validate_run_id(run_id)
    validate_filename(filename)
    base = os.path.realpath(_run_dir(data_dir, run_id))
    real = os.path.realpath(os.path.join(base, filename))
    if real != base and not real.startswith(base + os.sep):
        return None
    return real if os.path.isfile(real) else None


def delete_run(data_dir: str, run_id: str) -> bool:
    """Removes a run (folder + index entry). Returns False if it was not present."""
    validate_run_id(run_id)
    index = read_index(data_dir)
    kept = [r for r in index if r["id"] != run_id]
    if len(kept) == len(index):
        return False
    shutil.rmtree(_run_dir(data_dir, run_id), ignore_errors=True)
    _write_index(data_dir, kept)
    return True
